name:                hs
version:             0.1.0.2
github:              "cdornan/hs"
license:             BSD3
author:              "Chris Dornan <chris@chrisdornan.com>"
maintainer:          "Chris Dornan <chris@chrisdornan.com>"
copyright:           "2021 Chris Dornan"
category:            Development

extra-source-files:
- README.md
- ChangeLog.md

synopsis:             GHC-toolchain installer broker
description: |
  A tool for keeping track of where GHC installations have been placed and reporting
  that to the build managers (like @stack@ and @cabal-install@).

dependencies:
- base >= 4.7 && < 5
- containers
- data-default
- directory
- filepath
- enum-text
- fmt
- optparse-applicative
- possibly
- text
- typed-process

ghc-options:
- -Wall

library:
  source-dirs: src

executables:
  hs:
    main:                hs.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs
