name:                hs
version:             0.1.0.0
github:              "githubuser/hs"
license:             BSD3
author:              "Chris Dornan <chris@chrisdornan.com>"
maintainer:          "Chris Dornan <chris@chrisdornan.com>"
copyright:           "2021 Chris Dornan"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:             GHC bindist manager
description: |
  A tool for keeping track of where GHC installations have been placed and reporting
  that to the build managers.

dependencies:
- base >= 4.7 && < 5
- enum-text
- fmt
- optparse-applicative
- possibly
- text

library:
  source-dirs: src

executables:
  hs:
    main:                hs.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs
